import { useState } from "react";
import { Sparkles, Wand2, Lightbulb, ArrowUpDown, Plus, RefreshCw } from "lucide-react";
import api from "../services/api";
import { PageTitle } from "./Dashboard";
import { Button, Input, Textarea, Select, Badge, EmptyState } from "../components/UI";
import { useToast } from "../components/Toast";

export default function AI(){
 const toast=useToast();const [goal,setGoal]=useState("");const [tasks,setTasks]=useState([]);const [suggestions,setSuggestions]=useState([]);const [description,setDescription]=useState("");const [busy,setBusy]=useState(false);const [topic,setTopic]=useState("");
 async function generate(){if(!goal.trim())return toast.push("Describe your project goal first.","error");setBusy(true);try{const r=await api.post("/ai/generate-tasks",{goal});setTasks(r.data.tasks);toast.push(r.data.provider==="fallback"?"Generated with safe demo AI fallback.":"AI tasks generated.");}catch(e){toast.push(e.message,"error")}finally{setBusy(false)}}
 async function desc(){setBusy(true);try{setDescription((await api.post("/ai/generate-description",{topic})).data.description)}catch(e){toast.push(e.message,"error")}finally{setBusy(false)}}
 async function tips(){setBusy(true);try{setSuggestions((await api.post("/ai/suggestions",{stats:{}})).data.suggestions)}catch(e){toast.push(e.message,"error")}finally{setBusy(false)}}
 return <><PageTitle title="AI Productivity Assistant" subtitle="Turn a goal into practical next actions with intelligent assistance."/><div className="ai-grid"><section className="panel ai-main"><div className="ai-heading"><div className="ai-icon"><Sparkles/></div><div><h2>Generate a project plan</h2><p>Describe the outcome you want. TaskFlow AI will suggest structured tasks.</p></div></div><Textarea label="Project goal / description" rows="5" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Example: Build a responsive portfolio website for my internship applications..."/><Button loading={busy} onClick={generate}><Wand2/> Generate tasks</Button>{tasks.length?<div className="generated-list"><div className="generated-head"><h3>Generated tasks</h3><Button variant="ghost" onClick={generate}><RefreshCw/> Regenerate</Button></div>{tasks.map((t,i)=><div className="generated-task" key={i}><div className="number">{i+1}</div><div className="generated-copy"><input value={t.title} onChange={e=>setTasks(v=>v.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/><textarea value={t.description} onChange={e=>setTasks(v=>v.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><div><Badge tone={`priority-${(t.priority||"Medium").toLowerCase()}`}>{t.priority}</Badge><span>Suggested: {t.suggestedDueDate}</span></div></div></div>)}</div>:<EmptyState title="Your generated plan will appear here" description="Enter a goal above and generate tasks."/>}</section><aside className="ai-side"><div className="panel"><div className="panel-head"><h3>AI tools</h3><Sparkles/></div><Input label="Topic for description" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. student expense tracker"/><Button variant="secondary" loading={busy} onClick={desc}>Generate description</Button>{description&&<p className="ai-result">{description}</p>}<hr/><Button variant="secondary" loading={busy} onClick={tips}><Lightbulb/> Productivity suggestions</Button>{suggestions.map((s,i)=><div className="tip" key={i}><Lightbulb size={16}/>{s}</div>)}<hr/><p className="muted"><ArrowUpDown size={15}/> Generated content is editable. Review it before saving to your project.</p></div></aside></div></>;
}
