import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Eye, EyeOff, Sparkles } from "lucide-react";
import { Button, Input } from "../components/UI";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../components/Toast";

export function Login() {
  const [form,setForm]=useState({email:"",password:""}); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const {login}=useAuth(); const nav=useNavigate(); const toast=useToast();
  async function submit(e){e.preventDefault();setError("");if(!form.email||!form.password)return setError("Please enter email and password.");setLoading(true);try{await login(form.email,form.password);toast.push("Welcome back!");nav("/app");}catch(err){setError(err.message);}finally{setLoading(false);}}
  return <AuthLayout title="Welcome back" subtitle="Sign in to continue your work."><form onSubmit={submit} className="auth-form"><Input label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/><div className="password-wrap"><Input label="Password" type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div>{error&&<div className="form-error">{error}</div>}<label className="check"><input type="checkbox"/> Remember me</label><Button loading={loading} className="btn-full">Login</Button></form><p className="auth-switch">New to TaskFlow AI? <Link to="/register">Create an account</Link></p></AuthLayout>;
}
export function Register() {
  const [form,setForm]=useState({name:"",email:"",password:"",confirm:""}); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const {register}=useAuth(); const nav=useNavigate(); const toast=useToast();
  async function submit(e){e.preventDefault();setError("");if(form.name.trim().length<2)return setError("Name must be at least 2 characters.");if(form.password.length<8)return setError("Password must be at least 8 characters.");if(form.password!==form.confirm)return setError("Passwords do not match.");setLoading(true);try{await register({name:form.name,email:form.email,password:form.password});toast.push("Account created!");nav("/app");}catch(err){setError(err.message);}finally{setLoading(false);}}
  return <AuthLayout title="Create your workspace" subtitle="Start managing projects with a smarter workflow."><form onSubmit={submit} className="auth-form"><Input label="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/><Input label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/><div className="password-wrap"><Input label="Password" type={show?"text":"password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimum 8 characters"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div><Input label="Confirm password" type={show?"text":"password"} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} placeholder="Repeat password"/>{error&&<div className="form-error">{error}</div>}<Button loading={loading}>Create account</Button></form><p className="auth-switch">Already have an account? <Link to="/login">Login</Link></p></AuthLayout>;
}
function AuthLayout({title,subtitle,children}){return <div className="auth-page"><div className="auth-art"><Link to="/" className="brand"><div className="brand-mark">✦</div><div><b>TaskFlow</b><small>AI</small></div></Link><div><span className="eyebrow"><Sparkles/> Intelligent workspaces</span><h1>Turn busy work into clear progress.</h1><p>Projects, tasks and AI planning in a focused workspace.</p></div></div><div className="auth-panel"><div className="auth-box"><span className="eyebrow">TaskFlow AI</span><h2>{title}</h2><p>{subtitle}</p>{children}</div></div></div>}
