import { useEffect, useState } from "react";
import { FolderKanban, CheckSquare, CircleCheck, Clock3, Plus, ArrowRight, Activity as ActivityIcon } from "lucide-react";
import { Link } from "react-router-dom";
import api from "../services/api";
import StatCard from "../components/StatCard";
import { Button, LoadingSkeleton, EmptyState, ProgressBar, ErrorState } from "../components/UI";

export default function Dashboard() {
  const [data,setData]=useState(null),[projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[activity,setActivity]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(){setLoading(true);try{const [s,p,t,a]=await Promise.all([api.get("/dashboard/stats"),api.get("/projects"),api.get("/tasks"),api.get("/dashboard/activity")]);setData(s.data.stats);setProjects(p.data.projects.slice(0,4));setTasks(t.data.tasks.slice(0,5));setActivity(a.data.activity.slice(0,5));}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  if(loading)return <><PageTitle title="Dashboard" subtitle="Here’s what’s happening across your workspace."/><LoadingSkeleton count={6}/></>;
  if(error)return <ErrorState message={error} retry={load}/>;
  return <><PageTitle title="Good to see you." subtitle="Here’s what’s happening across your workspace." action={<Link to="/app/projects" className="btn btn-primary"><Plus size={18}/> New project</Link>}/><div className="stats-grid"><StatCard icon={FolderKanban} label="Total projects" value={data.totalProjects} detail="Across your workspace" accent="blue"/><StatCard icon={CheckSquare} label="Total tasks" value={data.totalTasks} detail={`${data.pendingTasks} still to do`} accent="pink"/><StatCard icon={CircleCheck} label="Completed" value={data.completedTasks} detail={`${data.completionRate}% completion rate`} accent="green"/><StatCard icon={Clock3} label="In progress" value={data.inProgressTasks} detail={`${data.urgentTasks} urgent`} accent="purple"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Projects</span><h3>Recent projects</h3></div><Link to="/app/projects" className="text-link">View all <ArrowRight size={15}/></Link></div>{projects.length?<div className="mini-projects">{projects.map(p=><Link className="mini-project" to={`/app/projects/${p._id}`} key={p._id}><div><b>{p.name}</b><small>{p.taskCount} tasks · {p.status}</small></div><div className="mini-progress"><strong>{p.progress}%</strong><ProgressBar value={p.progress}/></div></Link>)}</div>:<EmptyState title="No projects yet"/>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Tasks</span><h3>Recent tasks</h3></div><Link to="/app/tasks" className="text-link">View all <ArrowRight size={15}/></Link></div>{tasks.length?<div className="mini-tasks">{tasks.map(t=><div className="mini-task" key={t._id}><span className={`status-dot status-${t.status.replace(" ","-").toLowerCase()}`}/><div><b>{t.title}</b><small>{t.project?.name} · {t.priority}</small></div><span>{t.status}</span></div>)}</div>:<EmptyState title="No tasks yet"/>}</section></div><section className="panel activity-panel"><div className="panel-head"><div><span className="eyebrow">Timeline</span><h3>Recent activity</h3></div><ActivityIcon size={20}/></div>{activity.map(a=><div className="activity-row" key={a._id}><div className="activity-avatar">{a.user?.name?.[0]||"U"}</div><div><b>{a.description}</b><small>{new Date(a.createdAt).toLocaleString()}</small></div></div>)}</section></>;
}
export function PageTitle({title,subtitle,action}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
