import { Link } from "react-router-dom";
import { ArrowRight, Sparkles, FolderKanban, CheckCircle2, BarChart3, ShieldCheck, Zap } from "lucide-react";

export default function Landing() {
  return <div className="landing">
    <nav className="landing-nav"><Link className="brand" to="/"><div className="brand-mark">✦</div><div><b>TaskFlow</b><small>AI</small></div></Link><div className="landing-links"><a href="#features">Features</a><a href="#ai">AI</a><a href="#workflow">Workflow</a></div><div className="landing-actions"><Link to="/login" className="text-link">Login</Link><Link to="/register" className="btn btn-primary">Get Started</Link></div></nav>
    <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> AI-powered productivity</span><h1>Plan smarter.<br/><span>Work better.</span><br/>Achieve more.</h1><p>TaskFlow AI brings projects, tasks, analytics and intelligent planning into one beautifully simple workspace.</p><div className="hero-actions"><Link to="/register" className="btn btn-primary btn-lg">Start building <ArrowRight size={18}/></Link><Link to="/login" className="btn btn-secondary btn-lg">Explore dashboard</Link></div><div className="trust-row"><span><CheckCircle2/> Real-time progress</span><span><ShieldCheck/> Secure by design</span></div></div><div className="hero-visual"><div className="orb orb-blue"/><div className="orb orb-pink"/><div className="mock-window"><div className="mock-head"><span/><span/><span/></div><div className="mock-content"><div className="mock-stat"><b>84%</b><small>Productivity</small></div><div className="mock-bars"><i/><i/><i/><i/><i/></div><div className="mock-list"><div/><div/><div/></div></div></div></div></section>
    <section id="features" className="section"><div className="section-head"><span className="eyebrow">Everything in one place</span><h2>A calmer way to manage complex work.</h2></div><div className="feature-grid">{[[FolderKanban,"Projects","Plan projects, milestones, priorities and deadlines."],[CheckCircle2,"Tasks","Turn plans into focused work with clear status and ownership."],[BarChart3,"Analytics","See completion, priorities and productivity trends at a glance."],[Zap,"Automation","Use AI to turn a project goal into an actionable task plan."]].map(([I,t,d])=><div className="feature-card" key={t}><div className="feature-icon"><I/></div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
    <section id="ai" className="ai-section"><div><span className="eyebrow"><Sparkles/> TaskFlow intelligence</span><h2>Your project idea becomes a practical plan.</h2><p>Describe what you want to achieve. TaskFlow AI can generate structured tasks, suggest priorities and help you keep momentum.</p><Link to="/register" className="btn btn-primary">Try AI Assistant <ArrowRight/></Link></div><div className="ai-preview"><div className="ai-title"><Sparkles/> Project plan generated</div>{["Define success criteria","Create implementation plan","Build core functionality","Validate and test"].map((x,i)=><div className="ai-task" key={x}><span>{i+1}</span><b>{x}</b><small>{i<2?"High":"Medium"}</small></div>)}</div></section>
    <section id="workflow" className="section"><div className="section-head"><span className="eyebrow">Simple workflow</span><h2>From idea to done.</h2></div><div className="steps">{["Create a project","Generate or add tasks","Track progress","Learn from analytics"].map((x,i)=><div className="step" key={x}><strong>0{i+1}</strong><h3>{x}</h3><p>Keep the next action visible and the bigger goal in view.</p></div>)}</div></section>
    <section className="cta"><h2>Make your next project flow.</h2><p>One workspace for planning, execution and intelligent productivity.</p><Link to="/register" className="btn btn-white btn-lg">Create your workspace <ArrowRight/></Link></section>
    <footer><span>© 2026 TaskFlow AI</span><span>Plan smarter. Work better. Achieve more.</span></footer>
  </div>;
}
