import { useEffect, useMemo, useState } from "react";
import { Plus, Search, SlidersHorizontal } from "lucide-react";
import api from "../services/api";
import { PageTitle } from "./Dashboard";
import ProjectCard from "../components/ProjectCard";
import Modal from "../components/Modal";
import { Button, Input, Select, Textarea, LoadingSkeleton, EmptyState, ErrorState } from "../components/UI";
import { useToast } from "../components/Toast";

const blank={name:"",description:"",priority:"Medium",status:"Planning",startDate:"",dueDate:""};

export default function Projects(){
 const [projects,setProjects]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[q,setQ]=useState(""),[status,setStatus]=useState("All"),[priority,setPriority]=useState("All"),[sort,setSort]=useState("new"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""); const toast=useToast();
 async function load(){setLoading(true);try{setProjects((await api.get("/projects")).data.projects)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>projects.filter(p=>(p.name+p.description).toLowerCase().includes(q.toLowerCase())&&(status==="All"||p.status===status)&&(priority==="All"||p.priority===priority)).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="progress"?b.progress-a.progress:new Date(b.createdAt)-new Date(a.createdAt)),[projects,q,status,priority,sort]);
 function edit(p){setEditing(p);setForm({...blank,...p,startDate:p.startDate?.slice(0,10)||"",dueDate:p.dueDate?.slice(0,10)||""});setOpen(true)}
 async function save(e){e.preventDefault();setSaving(true);try{const payload={...form,startDate:form.startDate||undefined,dueDate:form.dueDate||undefined};if(editing)await api.put(`/projects/${editing._id}`,payload);else await api.post("/projects",payload);toast.push(editing?"Project updated":"Project created");setOpen(false);setEditing(null);setForm(blank);load()}catch(e){toast.push(e.message,"error")}finally{setSaving(false)}}
 async function del(id){if(!confirm("Delete this project and its tasks?"))return;try{await api.delete(`/projects/${id}`);toast.push("Project deleted");load()}catch(e){toast.push(e.message,"error")}}
 return <><PageTitle title="Projects" subtitle="Plan, prioritize and track every initiative." action={<Button onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus/> Create project</Button>}/><div className="toolbar"><div className="search-box"><Search/><input placeholder="Search projects..." value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Planning</option><option>Active</option><option>On Hold</option><option>Completed</option></Select><Select value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></Select><Select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Newest</option><option value="name">Name</option><option value="progress">Progress</option></Select><SlidersHorizontal className="filter-icon"/></div>{loading?<LoadingSkeleton count={4}/>:error?<ErrorState message={error} retry={load}/>:filtered.length?<div className="project-grid">{filtered.map(p=><ProjectCard key={p._id} project={p} onEdit={edit} onDelete={del}/>)}</div>:<EmptyState title="No matching projects" description="Try changing your search or filters, or create a new project."/>}<Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit project":"Create project"}><form className="form-grid" onSubmit={save}><Input label="Project name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Textarea label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="two-col"><Select label="Priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></Select><Select label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Planning</option><option>Active</option><option>On Hold</option><option>Completed</option></Select></div><div className="two-col"><Input label="Start date" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><Input label="Due date" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></div><Button loading={saving}>{editing?"Save changes":"Create project"}</Button></form></Modal></>;
}
