import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Plus, Sparkles, Trash2, Edit3 } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import api from "../services/api";
import { Badge, Button, EmptyState, LoadingSkeleton, ProgressBar } from "../components/UI";
import { PageTitle } from "./Dashboard";
import TaskCard from "../components/TaskCard";
import Modal from "../components/Modal";
import { Input, Textarea, Select } from "../components/UI";
import { useToast } from "../components/Toast";

export default function ProjectDetails(){
 const {id}=useParams();const nav=useNavigate();const toast=useToast();const [project,setProject]=useState(null),[loading,setLoading]=useState(true),[taskOpen,setTaskOpen]=useState(false),[task,setTask]=useState({title:"",description:"",priority:"Medium",status:"Todo",dueDate:""}),[saving,setSaving]=useState(false);
 async function load(){try{setProject((await api.get(`/projects/${id}`)).data.project)}catch(e){toast.push(e.message,"error")}finally{setLoading(false)}}useEffect(()=>{load()},[id]);
 async function createTask(e){e.preventDefault();setSaving(true);try{await api.post("/tasks",{...task,project:id,dueDate:task.dueDate||undefined});toast.push("Task created");setTaskOpen(false);setTask({title:"",description:"",priority:"Medium",status:"Todo",dueDate:""});load()}catch(e){toast.push(e.message,"error")}finally{setSaving(false)}}
 async function delTask(tid){try{await api.delete(`/tasks/${tid}`);toast.push("Task deleted");load()}catch(e){toast.push(e.message,"error")}}
 async function status(tid,s){try{await api.patch(`/tasks/${tid}/status`,{status:s});load()}catch(e){toast.push(e.message,"error")}}
 async function delProject(){if(!confirm("Delete this project and all tasks?"))return;try{await api.delete(`/projects/${id}`);toast.push("Project deleted");nav("/app/projects")}catch(e){toast.push(e.message,"error")}}
 if(loading)return <LoadingSkeleton count={5}/>; if(!project)return <EmptyState title="Project not found"/>;
 return <><Link className="back-link" to="/app/projects"><ArrowLeft size={16}/> Back to projects</Link><PageTitle title={project.name} subtitle={project.description||"No project description."} action={<div className="title-actions"><Button variant="secondary" onClick={()=>nav("/app/ai")}><Sparkles/> Generate with AI</Button><Button variant="danger" onClick={delProject}><Trash2/> Delete</Button></div>}/><div className="detail-top"><div className="detail-progress"><span>Overall progress</span><strong>{project.progress}%</strong><ProgressBar value={project.progress}/></div><div className="detail-chips"><Badge>{project.status}</Badge><Badge tone={`priority-${project.priority.toLowerCase()}`}>{project.priority}</Badge><span><CalendarDays/> {project.dueDate?new Date(project.dueDate).toLocaleDateString():"No due date"}</span></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Execution</span><h3>Project tasks</h3></div><Button onClick={()=>setTaskOpen(true)}><Plus/> Add task</Button></div>{project.tasks.length?<div className="task-list">{project.tasks.map(t=><TaskCard key={t._id} task={t} onStatus={status} onEdit={()=>toast.push("Edit tasks from Tasks page")} onDelete={delTask}/>)}</div>:<EmptyState title="No tasks yet" description="Add a task or use AI to generate a plan."/>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Timeline</span><h3>Activity history</h3></div></div>{project.activity?.length?project.activity.map(a=><div className="activity-row" key={a._id}><div className="activity-avatar">{a.user?.name?.[0]||"U"}</div><div><b>{a.description}</b><small>{new Date(a.createdAt).toLocaleString()}</small></div></div>):<EmptyState title="No activity yet"/>}</section></div><Modal open={taskOpen} onClose={()=>setTaskOpen(false)} title="Add task"><form className="form-grid" onSubmit={createTask}><Input label="Task title" required value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><Textarea label="Description" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><div className="two-col"><Select label="Priority" value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></Select><Select label="Status" value={task.status} onChange={e=>setTask({...task,status:e.target.value})}><option>Todo</option><option>In Progress</option><option>Done</option></Select></div><Input label="Due date" type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/><Button loading={saving}>Add task</Button></form></Modal></>;
}
